### PR TITLE
Show idle overlay when applets are viewed in an iframe

### PR DESCRIPTION
**Pull request by juliavdkris**
This adds an "idle" overlay when applets are viewed in an iframe. This way, the applets don't accidentally capture the scroll action when the user is scrolling through the book. The overlay is only enabled when the `iframe` URL parameter is set to true.

The overlay very subtly grays out the screen (not to get in the way of users who still want to see static images without interacting), and adds a small text in the top left corner.

image

&nbsp;

Questions for reviewers:
- How is the design of the overlay? Is it clear enough, and not too intrusive?
- How long should the timeout be to show it again after inactivity?

### CODE REVIEW

**Comment by yustarandomname** [comment]
Sliders should be immediately interactive. So in order of z-index: Controls -> Overlay -> Applet (2d/3d). When sliding, or in the new version clicking on a sliders should play the scene.

**Comment by juliavdkris** [comment]
@yustarandomname good point! I think style-wise it makes more sense to put the overlay on top though. I'll see if I can implement that idea I had before, where the same click that dismisses the overlay can also still turn the camera or change the sliders. I'm thinking that if I use the `mousedown` event instead of `click` and let it propagate, that might work?

Otherwise I'll do what you suggested, and put it below the sliders

**Comment by yustarandomname** [comment]
Another possibility that we could just disable the properties zoom & rotate of the Orbitcontrol in this file: [SetCamera.svelte](https://github.com/PRIME-TU-Delft/turborepo-visuals/blob/main/packages/threlte-components/components/SetCamera.svelte#L64-L70.).
Then when the applet has some form of interaction (click on sliders, info button, canvas, etc...) we activate the zoom and rotate again.

**Comment by yustarandomname** [comment]
Another thing to keep in mind is that the applet should go back to inactive after some time of inactivity. Otherwise the scroll capturing is still their just delayed.

**Comment by juliavdkris** [comment]
Oh yeah that might be better actually! I'll give that a try

And it does indeed already go back to inactive after 60s of inactivity :)

**Comment by yustarandomname** [comment]
is deprecated because PR #114 extends this PR

**Pull request closed without merging**
