### PR TITLE
Improve search applet - ADD YOUR PICTURE BELOW

### PR DESCRIPTION
**Pull request by yustarandomname**
## Before (left) and After (right)
Screenshot 2023-07-10 at 19 40 23

Besides the visual overhaul, this indexing page is redesigned with many more features compared to the previous version.
- Folders no longer need a +page.svelte file in each sub-folder to have the indexing work.
- Search actually works.
- Search has a fuzzy search (using fuse.js) to prohibit small typos.
- Each applet has a preview button to quickly inspect each applet in "iframe mode".

## !! TODO for all reviewers: 
Previously, we discussed that it's inappropriate to add individual credits in the embed and share window, as these credits will be directly included in the book. In my opinion, we should add individual credits to this indexing page because it will serve as a home page and entry point from all applets and will never be visible in the final book.

### To add your contribution:
- Open this branch (improve-search-applet)
- Add a profile picture in the `/apps/web/static/contributors` folder (Must be .png)
- Rename the image to your name (Capitalised and with spaces, for me that is "Abel de Bruijn.png") 
- Add your name and title to the list of contributors in [this file](https://github.com/PRIME-TU-Delft/Open-LA-Applets/pull/127/files#:~:text=let%20contributors).

Alternatively, you can also leave your profile picture in a comment on this pull request, along with a title of your choice.

### CODE REVIEW

**Comment by VandeBult** [comment]
Ik kan de naam van mijn foto niet hernoemen, noch mijn naam toevoegen aan "dit bestand". 
Verder weet ik niet wat ik verder nog moet reviewen; maar een kleine preview tijdens het zoeken (in te klappen?) lijkt me wel mooi.

**Comment by BEvanGelderen** [comment]
Beryl door Stephan Voogt

**Comment by ChristopheTUD** [comment]
Christophe_foto_MOOC

**Comment by TeunJa** [comment]
Author_TeunJanssen_BW

**Comment by yustarandomname** [comment]
7sfjpi

**Comment by yustarandomname** [comment]
A new PR will be created for those who have not yet added their profile image to the homescreen.

**Pull request merged**
